### PR TITLE
Verify data files can be parsed properly

### LINKED ISSUE #10: Verify that all data files can be parsed
We need a test that is executed by the `ci` task that will fail if any of the JSON files in the `data` directory cannot be parsed by the standard ruby JSON library.

### PR DESCRIPTION
**Pull request by rbalekai**
closes #10

### CODE REVIEW

File: test/locabulary_test.rb [hunk 1]
```diff
@@ -59,6 +59,12 @@ def test_active_nested_label_for_three_level
     expected_result = ["School of Architecture", "Center for Building Communities"]
     assert_equal(obtained_result, expected_result)
   end
+
+  def test_to_verify_data_files
+    Dir.glob(File.join(File.dirname(__FILE__), '../data/*.json')).each do |file|
+      assert_kind_of(Array, JSON.parse(File.read(file)))
```
Comment (jeremyf) [inline test/locabulary_test.rb]: Can you add an assertion that there are entries in the Dir.glob
